### ISSUE TITLE
story of season code

### ISSUE THREAD

**Issue by eeelkababs** [FlagBrew/Sharkive#80]
### Fill this for problems with codes in the database

* **Title ID**:  Story of Season : Trio of towns / 0019F500
* **Product code**:  CTR-P-BB3E
* **Game version**: in game menu says 1.1(the dlc update, but if checked with fbi, it says 1056(1.2.0)
### Not working codes

cheats like foodbuff and fantastic livestock(first 6) , cycle item and instant field growth doesn't work.

cheats like item x99 in bag works but only once, like you go into rosalina turn it on , it will make the item 99 but if you used the item it will decrease. if you go into the rosalina menu and quickly toggle between on and off, the cheat will apply again. is this intended? back when using ntr plugin , if i'm not mistaken it was a permanent effect until the codes were off, but sadly after updating to latest luma and later version of the game, the game will crash if i use ntr code so i can't test or use that one anymore.

**Comment by SpiredMoth** [comment]
The item cheats not remaining in effect while you have the code active is a known bug in Luma's cheat engine. It is fixed in the most recent nightly build of Luma.

The others might also be related to another cheat engine bug that has been fixed in the nightlies. Or they might just be bad codes, I don't know.

If you want to retest on the latest nightly, it can be found [here](https://github.com/Pirater12/luma-nightlies/releases/latest). Just grab the `boot.firm` from there and replace the one on the root of your SD and you're good to go.

**Comment by JourneyOver** [comment]
As noted by Spired please test with the latest nightly release of luma.

**Comment by kimstraza** [comment]
with nightly build , the remaining in effect while code is active cheat is fine ,

instant regrowth work on farm tile above the cellar.

food buff and fantastic livestock still doesn't show anything , it might be bad code.

**Comment by JourneyOver** [comment]
Thanks for the report, someone will remove the broken code when they get a chance as I am unavailable to do so myself as I currently don't have a computer to do so.
